import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AppSidebar, MobileSidebar } from "@/components/layout/app-sidebar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
           <div className="hidden md:block w-64 shrink-0 fixed inset-y-0 z-50">
              <AppSidebar className="w-full h-full" />
           </div>
           <div className="flex-1 flex flex-col md:pl-64 transition-all duration-300">
              <header className="md:hidden p-4 border-b flex items-center bg-background sticky top-0 z-40">
                 <MobileSidebar />
                 <span className="ml-2 font-bold text-lg">Brain Gym</span>
              </header>
              <main className="flex-1 overflow-y-auto p-4 md:p-8">
                 {children}
              </main>
           </div>
        </div>
      </body>
    </html>
  );
}
